/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/bulb.glb --transform 
Files: public/bulb.glb [1.32MB] > /Users/yariv/dev/riser/home/bulb-transformed.glb [50.62KB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bulb-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.342, 57.456, 0]}>
        <mesh geometry={nodes['Light_Bulb2-Mesh'].geometry} material={materials.metal006} />
        <mesh geometry={nodes['Light_Bulb2-Mesh_1'].geometry} material={materials.Mat} />
      </group>
    </group>
  )
}

useGLTF.preload('/bulb-transformed.glb')
