/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/rocket.glb --transform 
Files: public/rocket.glb [45.16KB] > /Users/yariv/dev/riser/home/rocket-transformed.glb [7.39KB] (84%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rocket-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder006.geometry} material={materials['08___Default']} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials['03___Default']} />
      <mesh geometry={nodes.Line006.geometry} material={materials['02___Default']} />
      <mesh geometry={nodes.Cylinder010.geometry} material={materials._crayfishdiffuse} />
    </group>
  )
}

useGLTF.preload('/rocket-transformed.glb')
