/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/tablet.glb --transform 
Files: public/tablet.glb [44.3KB] > /Users/yariv/dev/riser/home/tablet-transformed.glb [7.1KB] (84%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tablet-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ChamferBox001_1.geometry} material={materials['02___Default']} />
      <mesh geometry={nodes.ChamferBox001_1_1.geometry} material={materials['01___Default']} />
      <mesh geometry={nodes.ChamferBox001_1_2.geometry} material={materials['04___Default']} />
      <mesh geometry={nodes.ChamferCyl001.geometry} material={materials['03___Default']} />
    </group>
  )
}

useGLTF.preload('/tablet-transformed.glb')
